### PR TITLE
Fixing protocol urgent changes

### PR DESCRIPTION
**Pull request by TeToNN**
Urgent, app is currently non usable.

Protocol for format has changed

### CODE REVIEW

**Comment by NamTThai** [comment]
Do you have the key to build the app? Let me email it to you :) what's your email address?

**Comment by TeToNN** [comment]
bouvetcl at gmail com

On 1 August 2015 at 19:25, Nam Thai <notifications@github.com> wrote:

> Do you have the key to build the app? Let me email it to you :) what's
> your email address?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NamTThai/PokemonShowdownAndroidClient/pull/96#issuecomment-126938720>
> .
>



-- 
BOUVET Clément
bouvetcl@gmail.com
 (+33) 6 32 66 03 06

**Comment by TeToNN** [comment]
I dont have them, please send them :)

bouvetcl@gmail.com

**Comment by TeToNN** [comment]
I think i need the keystore/password and the key password, not sure i'll figure it out

**Comment by NamTThai** [comment]
Yeah you'll need password. Ill send it to you

**Comment by TeToNN** [comment]
I'm on skype allday long startingnow

**Pull request merged**
