### PR TITLE
Chatfix

### PR DESCRIPTION
**Pull request by TeToNN**
Ok here's how we gonna do it.

First we gonna have a new apk fixing chat issues (i broke everything, but it's fixed).
Then i'll investigate that battling bug you had, then we release chalelnges.

### CODE REVIEW

**Comment by TeToNN** [comment]
Also I can't seem to reproduce your bug :/

**Comment by NamTThai** [comment]
Hmm hope you have been playing double. I'll keep playing and see if I can reproduce it!

**Comment by TeToNN** [comment]
I did. Can we merge this chatfixing part?

**Comment by TeToNN** [comment]
Maybe you had a weak signal ?

**Pull request merged**
